services:
  postgres:
    image: postgres:17
    container_name: benchmark-postgres

    environment:
      POSTGRES_DB: benchmark
      POSTGRES_USER: benchmark
      POSTGRES_PASSWORD: benchmark

    ports:
      - "5432:5432"

    volumes:
      - benchmark_postgres_data:/var/lib/postgresql/data

volumes:
  benchmark_postgres_data: